# Generated by Django 3.2.5 on 2023-08-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
