# Generated by Django 3.2.5 on 2023-08-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0002_message_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='modified_by',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
