# Generated by Django 3.2.5 on 2023-05-01 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emetteur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.utilisateur')),
                ('is_emetteur', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.utilisateur',),
        ),
        migrations.CreateModel(
            name='Recepteur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.utilisateur')),
                ('is_receiver', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='date_creation')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reset_token', models.CharField(blank=True, max_length=255, null=True)),
                ('date_enregistrement', models.DateTimeField(blank=True, null=True)),
                ('date_expiration_token', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.utilisateur',),
        ),
    ]
